/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.meia_2020.meia;
import java.io.*;
import java.lang.Object;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author roche
 */
public class BackUpFrame extends javax.swing.JFrame {
    String BackupRoute;
    /** Creates new form BackUpFrame */
    public BackUpFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnRuta = new javax.swing.JButton();
        lblRuta = new javax.swing.JLabel();
        BtnRealizarBackup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ruta del backup");

        BtnRuta.setText("Escoger ruta para el Backup");
        BtnRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRutaActionPerformed(evt);
            }
        });

        lblRuta.setText("____");

        BtnRealizarBackup.setText("Realizar Backup");
        BtnRealizarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRealizarBackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnRealizarBackup)
                    .addComponent(lblRuta)
                    .addComponent(BtnRuta)
                    .addComponent(jLabel1))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRuta)
                .addGap(24, 24, 24)
                .addComponent(BtnRuta)
                .addGap(18, 18, 18)
                .addComponent(BtnRealizarBackup)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("lblRutaBackup");
        BtnRuta.getAccessibleContext().setAccessibleName("BtnRuta");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRutaActionPerformed
        // TODO add your handling code here:
        //Botón para buscar la ruta 
        String ruta;
        JFileChooser dialog = new JFileChooser();
        dialog.setDialogTitle("Escoja la ruta para el backup");
        dialog.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int valor = dialog.showSaveDialog(null);
        if (valor == JFileChooser.APPROVE_OPTION) {
            BackupRoute = dialog.getSelectedFile().getAbsolutePath();
            lblRuta.setText(BackupRoute);
            //hasta aquí ya llevo la ruta
        }
        else
        {
            showMessageDialog(null, "El usuario ha cancelado el backup");
        }
    }//GEN-LAST:event_BtnRutaActionPerformed

    private void BtnRealizarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRealizarBackupActionPerformed
        // TODO add your handling code here:
        File originalImages = new File("C:/MEIA/fotografia");
        File originalUsers = new File("C:/MEIA/usuario.txt");
        File originalUsersBinnacle = new File("C:/MEIA/desc_usuario.txt");
        
        File newDir = new File(BackupRoute + "/MEIA_Backup");
        if (!newDir.exists()) {
            newDir.mkdir();
        }
        
        File imagesBackup = new File(BackupRoute + "/MEIA_Backup/fotografia");
        File usersBackup = new File(BackupRoute + "/MEIA_Backup/usuario.txt");
        File binnacleBackup = new File(BackupRoute + "/MEIA_Backup/desc_usuario.txt");
        
        try
        {
            Files.copy(originalImages.toPath(), imagesBackup.toPath());
            Files.copy(originalUsers.toPath(), usersBackup.toPath());
            Files.copy(originalUsersBinnacle.toPath(), binnacleBackup.toPath());
        }
        catch(Exception e)
        {
            showMessageDialog(null, "El archivo que está intentando copiar no existe");
        }
    }//GEN-LAST:event_BtnRealizarBackupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BackUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BackUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BackUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BackUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRealizarBackup;
    private javax.swing.JButton BtnRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblRuta;
    // End of variables declaration//GEN-END:variables

}
