/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.meia_2020.meia;
import com.meia_2020.meia.models.Data;
import java.io.*;
import java.lang.Object;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author roche
 */
public class BackUpFrame extends javax.swing.JFrame {
    String BackupRoute;
    /** Creates new form BackUpFrame */
    public BackUpFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnRuta = new javax.swing.JButton();
        lblRuta = new javax.swing.JLabel();
        BtnRealizarBackup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ruta del backup");

        BtnRuta.setText("Escoger ruta para el Backup");
        BtnRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRutaActionPerformed(evt);
            }
        });

        lblRuta.setText("____");

        BtnRealizarBackup.setText("Realizar Backup");
        BtnRealizarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRealizarBackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRuta)
                    .addComponent(BtnRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(BtnRealizarBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRuta)
                .addGap(24, 24, 24)
                .addComponent(BtnRuta)
                .addGap(18, 18, 18)
                .addComponent(BtnRealizarBackup)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("lblRutaBackup");
        BtnRuta.getAccessibleContext().setAccessibleName("BtnRuta");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRutaActionPerformed
        // TODO add your handling code here:
        //Botón para buscar la ruta 
        String ruta;
        JFileChooser dialog = new JFileChooser();
        dialog.setDialogTitle("Escoja la ruta para el backup");
        dialog.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int valor = dialog.showSaveDialog(null);
        if (valor == JFileChooser.APPROVE_OPTION) {
            BackupRoute = dialog.getSelectedFile().getAbsolutePath();
            lblRuta.setText(BackupRoute);
            //hasta aquí ya llevo la ruta
        }
        else
        {
            showMessageDialog(null, "El usuario ha cancelado el backup");
        }
    }//GEN-LAST:event_BtnRutaActionPerformed

    private void BtnRealizarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRealizarBackupActionPerformed
        // TODO add your handling code here:
        File originalFile = new File("C:/MEIA");
        File backupDir = new File(BackupRoute + "/MEIA_Backup");
        if (!backupDir.exists()) {
            backupDir.mkdir();
        }
         
        if (Copiar(originalFile, backupDir)) {
            showMessageDialog(null, "El backup ha sido creado exitosamente.");
            File backupBinnacle = new File("C:/MEIA/bitacora_backup.txt");
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDateTime now = LocalDateTime.now();  
            if (backupBinnacle.exists()) {
                try
                {
                    FileInputStream stream = new FileInputStream(backupBinnacle);
                    byte[] data = new byte[(int) backupBinnacle.length()];
                    stream.read(data);
                    stream.close();
                    String file = new String(data, "UTF-8");
                    file += BackupRoute + "|" + Data.getInstance().usuarioActual.usuario + "|" + formatter.format(now) + "\r\n";
                    data = file.getBytes();
                    Files.write(backupBinnacle.toPath(), data);
                }
                catch (Exception e)
                {
                    showMessageDialog(null, "No se ha podido actualizar la bitácora del backup correctamente.");
                }
            }
            else
            {
                try
                {
                    String line = BackupRoute + "|" + Data.getInstance().usuarioActual.usuario + "|" + formatter.format(now) + "\r\n";
                    byte[] data = line.getBytes();
                    Files.write(backupBinnacle.toPath(), data);
                }
                catch (Exception e)
                {
                    showMessageDialog(null, "No se ha podido actualizar la bitácora del backup correctamente.");
                }
            }
        }
    }//GEN-LAST:event_BtnRealizarBackupActionPerformed

    private static boolean Copiar(File originalFile, File backupDir)
    {
        try
        {
            for (int i = 0; i < originalFile.listFiles().length; i++) {
                if (originalFile.listFiles()[i].isDirectory()) {
                    File newDir = new File(backupDir.toPath() + "/" + originalFile.listFiles()[i].getName());
                    if (!newDir.exists()) {
                        newDir.mkdir();
                    }
                    Copiar(originalFile.listFiles()[i], newDir);
                }
                else
                {
                    File originalFile2 = new File(originalFile.listFiles()[i].toString());
                    var newFile = new File(backupDir.toPath() + "/" + originalFile2.getName());
                    Files.copy(originalFile2.toPath(), newFile.toPath());
                }
            }
            return true;
        }
        catch(Exception e)
        {
            showMessageDialog(null, "El archivo que ha intentado copiar no existe o el backup ya ha sido creado en la dirección provista.");
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BackUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BackUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BackUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BackUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRealizarBackup;
    private javax.swing.JButton BtnRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblRuta;
    // End of variables declaration//GEN-END:variables

}
